import { generateAccessibleTextColor } from './generateAccessibleTextColor.js';
import { generateSecondaryColor } from './generateSecondaryColor.js';

export function applyLogoTheme(template, palette, options = {}) {
  if (!palette?.backgroundColor && !palette?.primaryColor) {
    return { ...template };
  }

  const backgroundColor = palette.backgroundColor || palette.primaryColor || template.backgroundColor;
  const foregroundColor = options.autoText !== false
    ? generateAccessibleTextColor(backgroundColor)
    : template.foregroundColor;

  const labelColor = options.autoText !== false
    ? (foregroundColor === '#ffffff' ? 'rgba(255,255,255,0.78)' : 'rgba(17,17,17,0.7)')
    : (template.labelColor || template.foregroundColor);

  const secondaryColor = options.autoSecondary !== false
    ? (palette.secondaryColor || generateSecondaryColor(backgroundColor))
    : template.secondaryColor;

  return {
    ...template,
    backgroundColor,
    foregroundColor,
    labelColor,
    primaryColor: palette.primaryColor || backgroundColor,
    secondaryColor,
    autoGeneratedFromLogo: true
  };
}
